### ISSUE TITLE
Revenge installer can only see 10 partitions

### ISSUE THREAD

**Issue by yrmvgh** [obrevenge/nemesis#1]
When attempting to install RevengeOS (arch) with a custom partitioning scheme, I was unable to use sda11 and above as the target.

**Comment by obrevenge** [comment]
Question, did the partitons sda11 and up show up, yet they could not be selected? Or were they not shown at all?

**Comment by obrevenge** [comment]
Ok, the code has been revised and I have tested it with up to 20 partitions. Feel free to re-open this issue if you have further problems.

-Jody
